# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_remove_book_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Identifiers',
            new_name='Identifier',
        ),
    ]
