# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='shrestha', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
